---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(stringr)
library(purrr)
library(ggplot2)
```

```{r}
contar_etiquetas <- function(number){
  read_csv(paste0("/home/pablo/DHARMA/identificaci-nDeRacimos/",number,"_etiquetas.txt"),
           col_names =FALSE, col_types = cols())$X1 %>% 
  map(read_csv) %>% bind_rows() %>%
  filter(label == "baya") %>%
  mutate(vid_name = word(img_name_0,1,sep = "_F")) %>%
  count(vid_name) %>% rename(bayas_etiquetadas = n) %>% mutate(corrida = number)
} 

contar_mappoints <- function(number){
  read_csv(paste0("/home/pablo/DHARMA/identificaci-nDeRacimos/",number,"_reconstruccion.txt"),
           col_names =FALSE,col_types = cols())$X1 %>% 
    map(read_csv) %>% bind_rows() %>%
    filter(label == "baya", frame_id == 0, Z!=0, X!=0, Y!=0) %>%
    mutate(vid_name = word(img_name,1,sep = "_F") ) %>%
    count(vid_name) %>% rename(bayas_reconstruidas = n) %>% mutate(corrida = number)
} 
```

```{r message=FALSE}
etiquetas <- c("01","03","13") %>% map(contar_etiquetas) %>% bind_rows()
mappoints <- c("01","03","13") %>% map(contar_mappoints) %>% bind_rows()

bayas_perdidas <- etiquetas %>% right_join(mappoints, by=c("vid_name","corrida")) %>% 
  mutate(ratio = bayas_reconstruidas/bayas_etiquetadas)

```

```{r}
ggplot(bayas_perdidas) + 
  geom_abline() +
  geom_point(aes(x =bayas_etiquetadas, y=bayas_reconstruidas)) +
  geom_smooth(aes(x =bayas_etiquetadas, y=bayas_reconstruidas)) +
  facet_wrap(~corrida)

ggplot(bayas_perdidas) +
  stat_ecdf(aes(x=ratio)) +
  scale_y_continuous(breaks = c(0.25,0.5,0.75,1) ) +
   scale_x_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
  xlab("reconstruidas/etiquetadas") +
  theme(
  panel.grid.major.x = element_line( size=.1, color="black" ),
           panel.grid.major.y = element_line( size=.1, color="black" )
    )

ggplot(bayas_perdidas) +
  geom_histogram(aes(x=ratio))
```

