---
title: "R Notebook"
output: html_notebook
---

Carga los índices de cada par de frames para saber cuales corresponden a cada racimo
```{r message=FALSE}
library(readr)
library(dplyr)
library(purrr)
library(tidyr)
buenas01 <- read_csv("../../input/nubes_completas/bonarda/frames01/buenas.csv")$img_name
buenas03 <- read_csv("../../input/nubes_completas/bonarda/frames03/buenas.csv")$img_name
buenas13 <- read_csv("../../input/nubes_completas/bonarda/frames13/buenas.csv")$img_name
```

Carga la info de los frames 01 vs 03
```{r message=FALSE}

setwd("../salidasICP/bonarda01_vs_bonarda03_sin_ruido")

df_01_03 <- "bonarda01_vs_bonarda03_sin_ruido" %>%
  paste0(c(0.1,0.2,0.3,0.4,0.5,1),".csv") %>% 
  map(read_csv) %>% bind_rows() %>% unique() %>%
  left_join(read_csv("nube1_names.csv")) %>%
  left_join(read_csv("nube2_names.csv")) %>% 
  filter(name1 %in% buenas01) %>% 
  filter(name1 %in% buenas03) %>% mutate(corrida = "01_03")
```

Carga la info de los frames 01 vs 13
```{r message=FALSE}
setwd("../salidasICP/bonarda01_vs_bonarda13_sin_ruido")

df_01_13 <- "bonarda01_vs_bonarda13_sin_ruido" %>%
  paste0(c(0.1,0.2,0.3,0.4,0.5,1),".csv") %>% 
  map(read_csv) %>% bind_rows() %>% unique() %>%
  left_join(read_csv("nube1_names.csv")) %>%
  left_join(read_csv("nube2_names.csv")) %>% 
  filter(name1 %in% buenas01) %>% 
  filter(name1 %in% buenas13) %>% mutate(corrida = "01_13")
```

Carga la info de los frames 03 vs 13
```{r message=FALSE}
setwd("../salidasICP/bonarda03_vs_bonarda13_sin_ruido")

df_03_13 <- "bonarda03_vs_bonarda13_sin_ruido" %>%
  paste0(c(0.1,0.2,0.3,0.4,0.5,1),".csv") %>% 
  map(read_csv) %>% bind_rows() %>% unique() %>%
  left_join(read_csv("nube1_names.csv")) %>%
  left_join(read_csv("nube2_names.csv")) %>% 
  filter(name1 %in% buenas03) %>% 
  filter(name1 %in% buenas13) %>% mutate(corrida = "03_13")
```

Junta toda la info en un solo dataframe
```{r}
df <- bind_rows(df_01_03,df_01_13,df_03_13) 
max_bayas <- df %>% drop_na() %>%  select(tamaño_nube1) %>% unique() %>% max()

```

Funciones para calcular F1
```{r}
getf1_data <- function(m, data){
  data %>% 
        mutate(label = name1 == name2) %>% 
        mutate(fitness = matcheos/tamaño_nube1) %>% 
        mutate(prediction = matcheos>m) %>%
        group_by(radio) %>% summarise(
        TP = sum(label==TRUE & prediction==TRUE),
        TN = sum(label==FALSE & prediction==FALSE),
        FP = sum(label==FALSE & prediction==TRUE),
        FN = sum(label==TRUE & prediction==FALSE),
        precission = TP/(TP+FP), recall = TP/(TP+FN),
        F1 = 2*(precission*recall)/(precission+recall)) %>% 
        mutate(m=m) 
} 

getf1_data_filter <- function(m, data){
  data %>%
    mutate(label = name1 == name2) %>% 
        filter(tamaño_nube1>m & tamaño_nube2>m) %>% 
        mutate(fitness = matcheos/tamaño_nube1) %>% 
        mutate(prediction = matcheos>m) %>%
        group_by(radio) %>% summarise(
        TP = sum(label==TRUE & prediction==TRUE),
        TN = sum(label==FALSE & prediction==FALSE),
        FP = sum(label==FALSE & prediction==TRUE),
        FN = sum(label==TRUE & prediction==FALSE),
        precission = TP/(TP+FP), recall = TP/(TP+FN),
        F1 = 2*(precission*recall)/(precission+recall)) %>% 
        mutate(m=m) 
} 

```


```{r}
f1_df <- 3:max_bayas %>% map(getf1_data,df) %>% bind_rows()
f1_df_01_03 <- 3:max_bayas %>% map(getf1_data,df_01_03) %>% bind_rows()
f1_df_01_13 <- 3:max_bayas %>% map(getf1_data,df_01_13) %>% bind_rows()
f1_df_03_13 <- 3:max_bayas %>% map(getf1_data,df_03_13) %>% bind_rows()
f1_data_filtered <- 3:max_bayas %>% map(getf1_data_filter,df) %>% bind_rows()
```

```{r}
library(ggplot2)
ggplot(f1_df) + 
  geom_line(aes(x = m, y = F1)) +
  geom_line(aes(x = m, y = precission, col="precission")) +
  geom_line(aes(x = m, y = recall, col ="recall")) +
  facet_wrap(~radio) +
  #xlim(3,15) +
   xlab("matcheos") +
  scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
   scale_x_continuous(limits=c(3,15),breaks = seq(0, max_bayas, by = 1)) +
  theme(
  panel.grid.major.x = element_line( size=.1, color="black" ),
           panel.grid.major.y = element_line( size=.1, color="black" )
    )

ggplot(f1_df_01_03) + 
  geom_line(aes(x = m, y = F1)) +
  geom_line(aes(x = m, y = precission, col="precission")) +
  geom_line(aes(x = m, y = recall, col ="recall")) +
  facet_wrap(~radio) +
  #xlim(3,15) +
   xlab("matcheos") +
  scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
   scale_x_continuous(limits=c(3,15),breaks = seq(0, max_bayas, by = 1)) +
  theme(
  panel.grid.major.x = element_line( size=.1, color="black" ),
           panel.grid.major.y = element_line( size=.1, color="black" )
    )

ggplot(f1_df_01_13) + 
  geom_line(aes(x = m, y = F1)) +
  geom_line(aes(x = m, y = precission, col="precission")) +
  geom_line(aes(x = m, y = recall, col ="recall")) +
  facet_wrap(~radio) +
  #xlim(3,15) +
   xlab("matcheos") +
  scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
   scale_x_continuous(limits=c(3,15),breaks = seq(0, max_bayas, by = 1)) +
  theme(
  panel.grid.major.x = element_line( size=.1, color="black" ),
           panel.grid.major.y = element_line( size=.1, color="black" )
    )

ggplot(f1_df_03_13) + 
  geom_line(aes(x = m, y = F1)) +
  geom_line(aes(x = m, y = precission, col="precission")) +
  geom_line(aes(x = m, y = recall, col ="recall")) +
  facet_wrap(~radio) +
  #xlim(3,15) +
   xlab("matcheos") +
  scale_y_continuous(breaks = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)) +
   scale_x_continuous(limits=c(3,15),breaks = seq(0, max_bayas, by = 1)) +
  theme(
  panel.grid.major.x = element_line( size=.1, color="black" ),
           panel.grid.major.y = element_line( size=.1, color="black" )
    )

ggplot(f1_data_filtered) + 
  geom_line(aes(x = m, y = F1)) +
  geom_line(aes(x = m, y = precission, col="precission")) +
  geom_line(aes(x = m, y = recall, col ="recall")) +
  facet_wrap(~radio) +
  #xlim(3,15) +
  xlab("matcheos")
```

```{r}
df %>% filter(label == TRUE) %>% ggplot + geom_histogram(aes(matcheos))
fallos <- df %>% mutate(label = name1 == name2) %>% filter(label==TRUE,matcheos<9,radio==0.3)

dfFalse <-  df %>% filter(nube1 == 43,radio==0.2)

```



